--- !ruby/object:Board 
postions: 
- !ruby/object:Position 
  name: Go
- !ruby/object:Position 
  name: Old Kent Road
- !ruby/object:Position 
  name: Community Chest
- !ruby/object:Position 
  name: Whitechapel Road
- !ruby/object:Position 
  name: Income Tax
- !ruby/object:Position 
  name: Kings Cross station
- !ruby/object:Position 
  name: The Angel Islington
- !ruby/object:Position 
  name: Chance
- !ruby/object:Position 
  name: Euston Road
- !ruby/object:Position 
  name: Pentonville Road
- !ruby/object:Position 
  name: In jail, Just visiting
- !ruby/object:Position 
  name: Pall Mall
- !ruby/object:Position 
  name: Electric Company
- !ruby/object:Position 
  name: Whitewall
- !ruby/object:Position 
  name: Northumberland
- !ruby/object:Position 
  name: Marylebone Station
- !ruby/object:Position 
  name: Bow Street
- !ruby/object:Position 
  name: Community Chest
- !ruby/object:Position 
  name: Marlborough Street
- !ruby/object:Position 
  name: Vine Street
- !ruby/object:Position 
  name: Free Parking
- !ruby/object:Position 
  name: Strand
- !ruby/object:Position 
  name: Chance
- !ruby/object:Position 
  name: Fleet Street
- !ruby/object:Position 
  name: Trafalgar Square
- !ruby/object:Position 
  name: Fenchurch Street
- !ruby/object:Position 
  name: Leicester Square
- !ruby/object:Position 
  name: Conventry Street
- !ruby/object:Position 
  name: Water Works
- !ruby/object:Position 
  name: Picadilly
- !ruby/object:Position 
  name: Go to jail
- !ruby/object:Position 
  name: Regent Street
- !ruby/object:Position 
  name: Oxford Street
- !ruby/object:Position 
  name: Community Chest
- !ruby/object:Position 
  name: Bond Street
- !ruby/object:Position 
  name: Liverpool Street station
- !ruby/object:Position 
  name: Chance
- !ruby/object:Position 
  name: Lane Park lane
- !ruby/object:Position 
  name: Super Tax
- !ruby/object:Position 
  name: Mayfair
