1: Go
2: Old Kent Road
3: Community Chest
4: Whitechapel Road
5: Income Tax
6: Kings Cross station
7: The Angel Islington
8: Chance
9: Euston Road
10: Pentonville Road
11: Jail
12: Pall Mall
13: Electric Company
14: Whitewall
15: Northumberland
16: Marylebone Station
17: Bow Street
18: Community Chest
19: Marlborough Street
20: Vine Street
21: Free Parking
22: Strand
23: Chance
24: Fleet Street
25: Trafalgar Square
26: Fenchurch Street
27: Leicester Square
28: Conventry Street
29: Water Works
30: Picadilly
31: Go to jail
32: Regent Street
33: Oxford Street
34: Community Chest
35: Bond Street
36: Liverpool Street station
37: Chance
38: Lane Park lane
39: Super Tax
40: Mayfair
